version: 0.2.{build}
environment:
  TARGET: x86_64-pc-windows-msvc
  RUST_BACKTRACE: 1
  matrix:
    - PYTHON: "C:/Python35-x64"
    - PYTHON: "C:/Python36-x64"

install:
  - python -V
  - ps: .\ci\appveyor\setup.ps1
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
  - rustc -V
  - cargo -V

build_script:
  - cargo build --verbose

before_test:
  - python -m pip install -U pip setuptools
  - pip install setuptools-rust pytest pytest-benchmark tox tox-venv

test_script:
  - ps: .\ci\appveyor\test.ps1
